-- CreateTable
CREATE TABLE "HanikamuActionLog" (
    "id" SERIAL NOT NULL,
    "actionId" INTEGER,
    "clickDateTime" TIMESTAMP(3),
    "actionDateTime" TIMESTAMP(3),
    "approvalDateTime" TIMESTAMP(3),
    "adName" TEXT,
    "adCategory" TEXT,
    "campaignName" TEXT,
    "landingPageName" TEXT,
    "lpUrl" TEXT,
    "deviceType" TEXT,
    "osType" TEXT,
    "status" TEXT,
    "referrerUrl" TEXT,
    "trackingParams" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "HanikamuActionLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WebantennaActionLog" (
    "id" SERIAL NOT NULL,
    "device_type" TEXT,
    "user_id" INTEGER,
    "session_id" INTEGER,
    "clicked" TIMESTAMP(3),
    "ad_authority" TEXT,
    "utm_sourc_identifier" TEXT,
    "utm_source" TEXT,
    "ad_identifier" TEXT,
    "campaign_name" TEXT,
    "ad_group_name" TEXT,
    "creative_name" TEXT,
    "creative_utm_name" TEXT,
    "ad_title" TEXT,
    "ad_url" TEXT,
    "cv_date" TIMESTAMP(3),
    "cv_name" TEXT,
    "cv_identifier_id" INTEGER,
    "course_name" TEXT,
    "course_name_detail" TEXT,
    "first_clicked" TIMESTAMP(3),
    "first_clicked_identifier" TEXT,
    "first_utm_source" TEXT,
    "first_ad_identifier" TEXT,
    "first_campaign_name" TEXT,
    "first_ad_group_name" TEXT,
    "first_creative_name" TEXT,
    "first_creative_utm_name" TEXT,
    "first_ad_title" TEXT,
    "first_ad_url" TEXT,
    "second_clicked" TIMESTAMP(3),
    "second_clicked_identifier" TEXT,
    "second_utm_source" TEXT,
    "second_ad_identifier" TEXT,
    "second_campaign_name" TEXT,
    "second_ad_group_name" TEXT,
    "second_creative_name" TEXT,
    "second_creative_utm_name" TEXT,
    "second_ad_title" TEXT,
    "second_ad_url" TEXT,
    "third_clicked" TIMESTAMP(3),
    "third_clicked_identifier" TEXT,
    "third_utm_source" TEXT,
    "third_ad_identifier" TEXT,
    "third_campaign_name" TEXT,
    "third_ad_group_name" TEXT,
    "third_creative_name" TEXT,
    "third_creative_utm_name" TEXT,
    "third_ad_title" TEXT,
    "third_ad_url" TEXT,
    "fourth_clicked" TIMESTAMP(3),
    "fourth_clicked_identifier" TEXT,
    "fourth_utm_source" TEXT,
    "fourth_ad_identifier" TEXT,
    "fourth_campaign_name" TEXT,
    "fourth_ad_group_name" TEXT,
    "fourth_creative_name" TEXT,
    "fourth_creative_utm_name" TEXT,
    "fourth_ad_title" TEXT,
    "fourth_ad_url" TEXT,
    "fifth_clicked" TIMESTAMP(3),
    "fifth_clicked_identifier" TEXT,
    "fifth_utm_source" TEXT,
    "fifth_ad_identifier" TEXT,
    "fifth_campaign_name" TEXT,
    "fifth_ad_group_name" TEXT,
    "fifth_creative_name" TEXT,
    "fifth_creative_utm_name" TEXT,
    "fifth_ad_title" TEXT,
    "fifth_ad_url" TEXT,
    "sixth_clicked" TIMESTAMP(3),
    "sixth_clicked_identifier" TEXT,
    "sixth_utm_source" TEXT,
    "sixth_ad_identifier" TEXT,
    "sixth_campaign_name" TEXT,
    "sixth_ad_group_name" TEXT,
    "sixth_creative_name" TEXT,
    "sixth_creative_utm_name" TEXT,
    "sixth_ad_title" TEXT,
    "sixth_ad_url" TEXT,
    "seventh_clicked" TIMESTAMP(3),
    "seventh_clicked_identifier" TEXT,
    "seventh_utm_source" TEXT,
    "seventh_ad_identifier" TEXT,
    "seventh_campaign_name" TEXT,
    "seventh_ad_group_name" TEXT,
    "seventh_creative_name" TEXT,
    "seventh_creative_utm_name" TEXT,
    "seventh_ad_title" TEXT,
    "seventh_ad_url" TEXT,
    "eighth_clicked" TIMESTAMP(3),
    "eighth_clicked_identifier" TEXT,
    "eighth_utm_source" TEXT,
    "eighth_ad_identifier" TEXT,
    "eighth_campaign_name" TEXT,
    "eighth_ad_group_name" TEXT,
    "eighth_creative_name" TEXT,
    "eighth_creative_utm_name" TEXT,
    "eighth_ad_title" TEXT,
    "eighth_ad_url" TEXT,
    "ninth_clicked" TIMESTAMP(3),
    "ninth_clicked_identifier" TEXT,
    "ninth_utm_source" TEXT,
    "ninth_ad_identifier" TEXT,
    "ninth_campaign_name" TEXT,
    "ninth_ad_group_name" TEXT,
    "ninth_creative_name" TEXT,
    "ninth_creative_utm_name" TEXT,
    "ninth_ad_title" TEXT,
    "ninth_ad_url" TEXT,
    "tenth_clicked" TIMESTAMP(3),
    "tenth_clicked_identifier" TEXT,
    "tenth_utm_source" TEXT,
    "tenth_ad_identifier" TEXT,
    "tenth_campaign_name" TEXT,
    "tenth_ad_group_name" TEXT,
    "tenth_creative_name" TEXT,
    "tenth_creative_utm_name" TEXT,
    "tenth_ad_title" TEXT,
    "tenth_ad_url" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WebantennaActionLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WebantennaClickLog" (
    "id" SERIAL NOT NULL,
    "ad_authority" TEXT,
    "channel" TEXT,
    "ad_identifier" TEXT,
    "campaign_name" TEXT,
    "ad_durations" TIMESTAMP(3),
    "click" INTEGER,
    "ec_registration_cv" INTEGER,
    "ec_direct_registration" INTEGER,
    "ec_revisit_registration" INTEGER,
    "ec_registration_cvr" INTEGER,
    "ec_purchase_cv" INTEGER,
    "ec_direct_purchase_cv" INTEGER,
    "ec_revisit_purchase_cv" INTEGER,
    "ec_purchase_cvr" INTEGER,
    "web_reservation_cv" INTEGER,
    "web_direct_reservation_cv" INTEGER,
    "web_revisit_reservation_cv" INTEGER,
    "web_reservation_cvr" DOUBLE PRECISION,
    "epiler_web_reservation_cv" INTEGER,
    "epiler_direct_reservation_cv" INTEGER,
    "epiler_revisit_reservation_cv" INTEGER,
    "epiler_web_reservation_cvr" DOUBLE PRECISION,
    "test1_cv" INTEGER,
    "test1_direct_cv" INTEGER,
    "test1_revisit_cv" INTEGER,
    "test1_cvr" DOUBLE PRECISION,
    "test2_cv" INTEGER,
    "test2_direct_cv" INTEGER,
    "test2_revisit_cv" INTEGER,
    "test2_cvr" DOUBLE PRECISION,
    "test3_cv" INTEGER,
    "test3_direct_cv" INTEGER,
    "test3_revisit_cv" INTEGER,
    "test3_cvr" DOUBLE PRECISION,
    "recruitment_cv" INTEGER,
    "recruitment_direct_cv" INTEGER,
    "recruitment_revisit_cv" INTEGER,
    "recruitment_cvr" DOUBLE PRECISION,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WebantennaClickLog_pkey" PRIMARY KEY ("id")
);
