-- CreateTable
CREATE TABLE "ActionLog" (
    "id" SERIAL NOT NULL,
    "actionDateTime" TIMESTAMP(3),
    "clickDateTime" TIMESTAMP(3),
    "adminDateTime" TIMESTAMP(3),
    "clientId" INTEGER,
    "clientName" TEXT,
    "contentId" INTEGER,
    "contentName" TEXT,
    "partnerId" INTEGER,
    "partnerName" TEXT,
    "groupId" INTEGER,
    "groupName" TEXT,
    "siteId" INTEGER,
    "siteName" TEXT,
    "actionCareer" TEXT,
    "actionOs" TEXT,
    "actionUserAgent" TEXT,
    "actionIpAddress" TEXT,
    "actionReferrer" TEXT,
    "queryString" TEXT,
    "clickPartnerInfo" TEXT,
    "clientInfo" TEXT,
    "sessionId" TEXT,
    "actionId" TEXT,
    "contentBannerNum" TEXT,
    "clientClickCost" DECIMAL(10,2),
    "partnerClickCost" DECIMAL(10,2),
    "clientCommissionCost" DECIMAL(10,2),
    "partnerCommissionCost" DECIMAL(10,2),
    "clientActionCost" DECIMAL(10,2),
    "partnerActionCost" DECIMAL(10,2),
    "actionType" INTEGER,
    "tierCommissionCost" DECIMAL(10,2),
    "status" TEXT,
    "amount" INTEGER,
    "comment" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ActionLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ClickLog" (
    "id" SERIAL NOT NULL,
    "actionDateTime" TEXT,
    "clickDateTime" TEXT,
    "admitDateTime" TEXT,
    "clientId" TEXT,
    "clientName" TEXT,
    "contentId" TEXT,
    "contentName" TEXT,
    "partnerId" TEXT,
    "partnerName" TEXT,
    "groupId" TEXT,
    "groupName" TEXT,
    "siteId" TEXT,
    "siteName" TEXT,
    "actionCareer" TEXT,
    "actionOs" TEXT,
    "actionUserAgent" TEXT,
    "actionIpAddress" TEXT,
    "actionReferrer" TEXT,
    "queryString" TEXT,
    "clickPartnerInfo" TEXT,
    "clientInfo" TEXT,
    "sessionId" TEXT,
    "actionId" TEXT,
    "contentBannerNum" TEXT,
    "clientClickCost" TEXT,
    "partnerClickCost" TEXT,
    "clientCommissionCost" TEXT,
    "partnerCommissionCost" TEXT,
    "clientActionCost" TEXT,
    "partnerActionCost" TEXT,
    "actionType" TEXT,
    "status" TEXT,
    "amount" TEXT,
    "comment" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ClickLog_pkey" PRIMARY KEY ("id")
);
