-- CreateTable
CREATE TABLE "AdebisActionLog" (
    "id" SERIAL NOT NULL,
    "cvName" TEXT,
    "cvDate" TIMESTAMP(3),
    "userId" TEXT,
    "userName" TEXT,
    "salesAmount" TEXT,
    "item1" TEXT,
    "item2" INTEGER,
    "item3" TEXT,
    "deviceType" TEXT,
    "latencyPeriod" TIMESTAMP(3),
    "latencyPeriodSeconds" INTEGER,
    "contactCount" INTEGER,
    "directConversionDate" TIMESTAMP(3),
    "directMediaCategory" TEXT,
    "directAdgroup" TEXT,
    "directAdName" TEXT,
    "directAdId" INTEGER,
    "indirectConversion2Date" TIMESTAMP(3),
    "indirectMediaCategory2" TEXT,
    "indirectAdgroup2" TEXT,
    "indirectAdName2" TEXT,
    "indirectAdId2" TEXT,
    "indirectConversion3Date" TIMESTAMP(3),
    "indirectMediaCategory3" TEXT,
    "indirectAdgroup3" TEXT,
    "indirectAdName3" TEXT,
    "indirectAdId3" TEXT,
    "indirectConversion4Date" TIMESTAMP(3),
    "indirectMediaCategory4" TEXT,
    "indirectAdgroup4" TEXT,
    "indirectAdName4" TEXT,
    "indirectAdId4" TEXT,
    "indirectConversion5Date" TIMESTAMP(3),
    "indirectMediaCategory5" TEXT,
    "indirectAdgroup5" TEXT,
    "indirectAdName5" TEXT,
    "indirectAdId5" TEXT,
    "indirectConversion6Date" TIMESTAMP(3),
    "indirectMediaCategory6" TEXT,
    "indirectAdgroup6" TEXT,
    "indirectAdName6" TEXT,
    "indirectAdId6" TEXT,
    "indirectConversion7Date" TIMESTAMP(3),
    "indirectMediaCategory7" TEXT,
    "indirectAdgroup7" TEXT,
    "indirectAdName7" TEXT,
    "indirectAdId7" TEXT,
    "indirectConversion8Date" TIMESTAMP(3),
    "indirectMediaCategory8" TEXT,
    "indirectAdgroup8" TEXT,
    "indirectAdName8" TEXT,
    "indirectAdId8" TEXT,
    "indirectConversion9Date" TIMESTAMP(3),
    "indirectMediaCategory9" TEXT,
    "indirectAdgroup9" TEXT,
    "indirectAdName9" TEXT,
    "indirectAdId9" TEXT,
    "indirectConversion10Date" TIMESTAMP(3),
    "indirectMediaCategory10" TEXT,
    "indirectAdgroup10" TEXT,
    "indirectAdName10" TEXT,
    "indirectAdId10" TEXT,
    "firstConversionDate" TIMESTAMP(3),
    "firstMediaType" TEXT,
    "firstAdName" TEXT,
    "firstAdId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AdebisActionLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AdebisClickLog" (
    "id" SERIAL NOT NULL,
    "mediaType" TEXT,
    "adgroup1" TEXT,
    "adgroup2" TEXT,
    "adId" TEXT,
    "adName" TEXT,
    "impressionCount" INTEGER,
    "clickData" INTEGER,
    "cvPaymentCount" INTEGER,
    "cvrPaymentCount" INTEGER,
    "cvTotal" INTEGER,
    "cvrTotal" INTEGER,
    "indirectConversion2" INTEGER,
    "indirectConversion3" INTEGER,
    "indirectConversion4" INTEGER,
    "indirectConversion5" INTEGER,
    "indirectConversion6" INTEGER,
    "indirectConversionTotal" INTEGER,
    "firstContact" INTEGER,
    "reallocatedCv" DOUBLE PRECISION,
    "salesAmount" TEXT,
    "adCost" TEXT,
    "cpa" TEXT,
    "tcpa" TEXT,
    "roas" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AdebisClickLog_pkey" PRIMARY KEY ("id")
);
