-- CreateTable
CREATE TABLE "ladActionLog" (
    "id" SERIAL NOT NULL,
    "actionDate" TIMESTAMP(3),
    "clickDate" TIMESTAMP(3),
    "midClickDate" TIMESTAMP(3),
    "mediaName" TEXT,
    "mediaCategory1" TEXT,
    "mediaCategory2" TEXT,
    "advertiserName" TEXT,
    "adName" TEXT,
    "adgroupName" TEXT,
    "conversionPointName" TEXT,
    "trackingUserId" TEXT,
    "salesAmount" INTEGER,
    "rewardAmount" INTEGER,
    "redirectAdUrlName" TEXT,
    "useRotation" TEXT,
    "carrier" TEXT,
    "osType" TEXT,
    "userAgentClick" TEXT,
    "userAgentAction" TEXT,
    "userIpClick" TEXT,
    "userIpAction" TEXT,
    "referrerClickUrl" TEXT,
    "lineName" TEXT,
    "lineUserId" TEXT,
    "lineUserName" TEXT,
    "clData1" TEXT,
    "catsReportId" TEXT,
    "midClData1" TEXT,
    "actionInfo1" TEXT,
    "sessionId" TEXT,
    "userId" TEXT,
    "midClickCount" INTEGER,
    "createdDate" TIMESTAMP(3),
    "updatedDate" TIMESTAMP(3),

    CONSTRAINT "ladActionLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ladClickLog" (
    "id" SERIAL NOT NULL,
    "clickDate" TIMESTAMP(3),
    "mediaName" TEXT,
    "mediaCategory1" TEXT,
    "mediaCategory2" TEXT,
    "advertiserName" TEXT,
    "adName" TEXT,
    "adgroupName" TEXT,
    "redirectAdUrlName" TEXT,
    "useRotation" TEXT,
    "carrier" TEXT,
    "osType" TEXT,
    "userAgent" TEXT,
    "ipAdress" TEXT,
    "referrer" TEXT,
    "clData1" TEXT,
    "facebookClId" TEXT,
    "yafooSearchAdClId" TEXT,
    "tiktokClId" TEXT,
    "googleClId" TEXT,
    "googleGbrald" TEXT,
    "googleWbrald" TEXT,
    "xClId" TEXT,
    "catsReportId" TEXT,
    "sessionId" TEXT,
    "userId" TEXT,
    "trackingUserId" TEXT,
    "status" TEXT,
    "createdDate" TIMESTAMP(3),
    "updatedDate" TIMESTAMP(3),

    CONSTRAINT "ladClickLog_pkey" PRIMARY KEY ("id")
);
